from django.urls import path, re_path

from . import docs_views, views

app_name = 'main'

urlpatterns = [
    path("favicon.ico", views.favicon_ico, name="favicon_ico"),
    path("robots.txt", views.robots_txt, name="robots_txt"),
    path("sitemap.xml", views.sitemap_xml, name="sitemap_xml"),
    # PWA endpoints (manifest + service worker)
    path("manifest.webmanifest", views.pwa_manifest, name="pwa_manifest"),
    path("service-worker.js", views.service_worker, name="service_worker"),
    path('', views.none, name='none'),
    path('ide', docs_views.docs_root_legacy_redirect, name='docs_root'),
    path('ide/', docs_views.docs_root_legacy_redirect),
    path('ide/list', docs_views.docs_list_root_legacy_redirect, name='docs_list_root'),
    path('ide/list/', docs_views.docs_list_root_legacy_redirect),
    path('ide/write', docs_views.docs_write_legacy_redirect, name='docs_write'),
    path('ide/write/', docs_views.docs_write_legacy_redirect),
    path('signup', docs_views.docs_signup, name='docs_signup'),
    path('signup/', docs_views.docs_signup),
    path('login', docs_views.docs_login, name='docs_login'),
    path('login/', docs_views.docs_login),
    path('logout', docs_views.docs_logout, name='docs_logout'),
    path('logout/', docs_views.docs_logout),
    path('ide/ops/apply-static', docs_views.docs_ops_apply_static, name='docs_ops_apply_static'),
    path('ide/ops/apply-static/', docs_views.docs_ops_apply_static),
    path('ide/api/list', docs_views.docs_api_list, name='docs_api_list'),
    path('ide/api/save', docs_views.docs_api_save, name='docs_api_save'),
    path('ide/api/preview', docs_views.docs_api_preview, name='docs_api_preview'),
    path('ide/api/rename', docs_views.docs_api_rename, name='docs_api_rename'),
    path('ide/api/delete', docs_views.docs_api_delete, name='docs_api_delete'),
    path('ide/api/mkdir', docs_views.docs_api_mkdir, name='docs_api_mkdir'),
    path('ide/api/move', docs_views.docs_api_move, name='docs_api_move'),
    path('ide/api/download', docs_views.docs_api_download, name='docs_api_download'),
    path('ide/api/acl', docs_views.docs_api_acl, name='docs_api_acl'),
    path('ide/api/acl-options', docs_views.docs_api_acl_options, name='docs_api_acl_options'),
    path('ide/api/url-share', docs_views.docs_api_url_share, name='docs_api_url_share'),
    path('ide/api/login-captcha-status', docs_views.docs_api_login_captcha_status, name='docs_api_login_captcha_status'),
    path('ide/share/<str:owner_username>/<str:share_slug>', docs_views.docs_shared_view, name='docs_shared_view'),
    path('ide/share/<str:owner_username>/<str:share_slug>/', docs_views.docs_shared_view),
    path('ide/<path:folder_path>/list', docs_views.docs_list_legacy_redirect, name='docs_list'),
    path('ide/<path:folder_path>/list/', docs_views.docs_list_legacy_redirect),
    path('ide/<path:doc_path>', docs_views.docs_view_legacy_redirect, name='docs_view'),
    re_path(r'^(?P<ui_lang>ko|en)/ide/?$', docs_views.docs_root, name='docs_root_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/ide/list/?$', docs_views.docs_root, name='docs_list_root_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/ide/write/?$', docs_views.docs_write, name='docs_write_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/signup/?$', docs_views.docs_signup, name='docs_signup_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/login/?$', docs_views.docs_login, name='docs_login_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/logout/?$', docs_views.docs_logout, name='docs_logout_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/ide/ops/apply-static/?$', docs_views.docs_ops_apply_static, name='docs_ops_apply_static_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/ide/share/(?P<owner_username>[^/]+)/(?P<share_slug>[^/]+)/?$', docs_views.docs_shared_view, name='docs_shared_view_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/ide/(?P<folder_path>.+)/list/?$', docs_views.docs_list, name='docs_list_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/ide/(?P<doc_path>.+)/?$', docs_views.docs_view, name='docs_view_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/$', views.none, name='none_lang'),
    path('docs', docs_views.docs_root_legacy_redirect),
    path('docs/', docs_views.docs_root_legacy_redirect),
    path('docs/list', docs_views.docs_list_root_legacy_redirect),
    path('docs/list/', docs_views.docs_list_root_legacy_redirect),
    path('docs/write', docs_views.docs_write_legacy_redirect),
    path('docs/write/', docs_views.docs_write_legacy_redirect),
    path('docs/ops/apply-static', docs_views.docs_ops_apply_static),
    path('docs/ops/apply-static/', docs_views.docs_ops_apply_static),
    path('docs/api/list', docs_views.docs_api_list),
    path('docs/api/save', docs_views.docs_api_save),
    path('docs/api/preview', docs_views.docs_api_preview),
    path('docs/api/rename', docs_views.docs_api_rename),
    path('docs/api/delete', docs_views.docs_api_delete),
    path('docs/api/mkdir', docs_views.docs_api_mkdir),
    path('docs/api/move', docs_views.docs_api_move),
    path('docs/api/download', docs_views.docs_api_download),
    path('docs/api/acl', docs_views.docs_api_acl),
    path('docs/api/acl-options', docs_views.docs_api_acl_options),
    path('docs/api/url-share', docs_views.docs_api_url_share),
    path('docs/api/login-captcha-status', docs_views.docs_api_login_captcha_status),
    path('docs/<path:folder_path>/list', docs_views.docs_list_legacy_redirect),
    path('docs/<path:folder_path>/list/', docs_views.docs_list_legacy_redirect),
    path('docs/<path:doc_path>', docs_views.docs_view_legacy_redirect),
    re_path(r'^(?P<ui_lang>ko|en)/portfolio/$', views.portfolio_root_redirect, name='main_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/portfolio/write/?$', views.portfolio_write, name='portfolio_write_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/portfolio/(?P<user_id>[A-Za-z0-9_.-]+)/$', views.portfolio_user, name='portfolio_user_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/project/(?P<project_id>\d+)/$', views.ProjectDetail, name='ProjectDetail_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/project/sample/(?P<sample_id>\d+)/$', views.DummyProjectDetail, name='DummyProjectDetail_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/project/(?P<user_id>[A-Za-z0-9_.-]+)/(?P<project_number>\d+)/$', views.ProjectDetailByUser, name='ProjectDetail_user_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/Salvations_Edge_4/$', views.Salvations_Edge_4, name='Salvations_Edge_4_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/Stratagem_Hero/$', views.Stratagem_Hero_page, name='Stratagem_Hero_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/Stratagem_Hero/Scoreboard/$', views.Stratagem_Hero_Scoreboard_page, name='Stratagem_Hero_Scoreboard_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/minigame/?$', views.minigame_page, name='minigame_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/bubble/?$', views.bubble_page, name='bubble_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/bumpercar-spiky/admin/?$', views.bumpercar_spiky_admin_page, name='bumpercar_spiky_admin_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/bumpercar-spiky/set-npc-health/?$', views.bumpercar_spiky_set_npc_health, name='bumpercar_spiky_set_npc_health_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/bumpercar-spiky/restart-server/?$', views.bumpercar_spiky_restart_server, name='bumpercar_spiky_restart_server_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/bumpercar-spiky/?$', views.hanplanet_multiplayer_page, name='bumpercar_spiky_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/Stratagem_Hero/add_score/$', views.add_score, name='add_score_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/Salvations_Edge_4/$', views.salvations_edge_legacy_redirect),
    re_path(r'^(?P<ui_lang>ko|en)/Stratagem_Hero/$', views.stratagem_hero_legacy_redirect),
    re_path(r'^(?P<ui_lang>ko|en)/Stratagem_Hero/Scoreboard/$', views.stratagem_hero_scoreboard_legacy_redirect),
    re_path(r'^(?P<ui_lang>ko|en)/minigame/?$', views.minigame_legacy_redirect),
    re_path(r'^(?P<ui_lang>ko|en)/bubble/?$', views.bubble_legacy_redirect),
    re_path(r'^(?P<ui_lang>ko|en)/hanplanet-multiplayer/?$', views.hanplanet_multiplayer_legacy_redirect),
    re_path(r'^(?P<ui_lang>ko|en)/bumpercar-spiky/?$', views.hanplanet_multiplayer_legacy_redirect),
    re_path(r'^(?P<ui_lang>ko|en)/Stratagem_Hero/add_score/$', views.add_score),
    re_path(r'^(?P<ui_lang>ko|en)/comment/create/(?P<project_id>\d+)/$', views.ProjectComment_create, name='ProjectComment_create_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/root-shortcuts/$', views.root_shortcuts, name='root_shortcuts_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/root-shortcuts/reorder/$', views.root_shortcuts_reorder, name='root_shortcuts_reorder_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/root-shortcuts/(?P<shortcut_id>\d+)/$', views.root_shortcuts_detail, name='root_shortcuts_detail_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/theme-preference/$', views.theme_preference, name='theme_preference_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/user-preferences/$', views.user_preferences, name='user_preferences_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/game-auth-token/$', views.game_auth_token, name='game_auth_token_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/account/profile-image/?$', views.account_profile_image_upload, name='account_profile_image_upload_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/chat/$', views.chat_with_ai, name='chat_with_ai_lang'),
    path('portfolio/', views.main_legacy_redirect, name='main'),
    path('portfolio/write', views.portfolio_write_legacy_redirect, name='portfolio_write_no_slash'),
    path('portfolio/write/', views.portfolio_write_legacy_redirect, name='portfolio_write'),
    path('portfolio/<str:user_id>/', views.portfolio_user_legacy_redirect, name='portfolio_user'),
    path('project/<int:project_id>/', views.project_detail_legacy_redirect, name='ProjectDetail'),
    path('project/<str:user_id>/<int:project_number>/', views.project_detail_user_legacy_redirect, name='ProjectDetail_user'),
    path('project/sample/<int:sample_id>/', views.dummy_project_detail_legacy_redirect, name='DummyProjectDetail'),
    path('fun/Salvations_Edge_4/', views.salvations_edge_legacy_redirect, name='Salvations_Edge_4'),
    path('fun/Stratagem_Hero/', views.stratagem_hero_legacy_redirect, name='Stratagem_Hero'),
    path('fun/Stratagem_Hero/Scoreboard/', views.stratagem_hero_scoreboard_legacy_redirect, name='Stratagem_Hero_Scoreboard'),
    path('fun/minigame', views.minigame_legacy_redirect, name='minigame_no_slash'),
    path('fun/minigame/', views.minigame_legacy_redirect, name='minigame'),
    path('fun/bubble', views.bubble_legacy_redirect, name='bubble_no_slash'),
    path('fun/bubble/', views.bubble_legacy_redirect, name='bubble'),
    path('fun/hanplanet-multiplayer', views.hanplanet_multiplayer_legacy_redirect, name='hanplanet_multiplayer_no_slash'),
    path('fun/hanplanet-multiplayer/', views.hanplanet_multiplayer_legacy_redirect, name='hanplanet_multiplayer'),
    path('fun/bumpercar-spiky', views.hanplanet_multiplayer_legacy_redirect, name='bumpercar_spiky_no_slash'),
    path('fun/bumpercar-spiky/admin', views.bumpercar_spiky_admin_legacy_redirect, name='bumpercar_spiky_admin_no_slash'),
    path('fun/bumpercar-spiky/admin/', views.bumpercar_spiky_admin_legacy_redirect, name='bumpercar_spiky_admin'),
    path('fun/bumpercar-spiky/', views.hanplanet_multiplayer_legacy_redirect, name='bumpercar_spiky'),
    path('fun/Stratagem_Hero/add_score/', views.add_score, name='add_score'),
    path('Salvations_Edge_4/', views.salvations_edge_legacy_redirect),
    path('Stratagem_Hero/', views.stratagem_hero_legacy_redirect),
    path('Stratagem_Hero/Scoreboard/', views.stratagem_hero_scoreboard_legacy_redirect),
    path('minigame', views.minigame_legacy_redirect),
    path('minigame/', views.minigame_legacy_redirect),
    path('bubble', views.bubble_legacy_redirect),
    path('bubble/', views.bubble_legacy_redirect),
    path('hanplanet-multiplayer', views.hanplanet_multiplayer_legacy_redirect),
    path('hanplanet-multiplayer/', views.hanplanet_multiplayer_legacy_redirect),
    path('bumpercar-spiky', views.hanplanet_multiplayer_legacy_redirect),
    path('bumpercar-spiky/', views.hanplanet_multiplayer_legacy_redirect),
    path('Stratagem_Hero/add_score/', views.add_score),
    path('comment/create/<int:project_id>/', views.ProjectComment_create, name='ProjectComment_create'),
    path('api/root-shortcuts/', views.root_shortcuts, name='root_shortcuts'),
    path('api/root-shortcuts/reorder/', views.root_shortcuts_reorder, name='root_shortcuts_reorder'),
    path('api/root-shortcuts/<int:shortcut_id>/', views.root_shortcuts_detail, name='root_shortcuts_detail'),
    path('api/theme-preference/', views.theme_preference, name='theme_preference'),
    path('api/user-preferences/', views.user_preferences, name='user_preferences'),
    path('api/game-auth-token/', views.game_auth_token, name='game_auth_token'),
    path('api/internal/bumpercar-spiky/stats/', views.bumpercar_spiky_stats_record, name='bumpercar_spiky_stats_record'),
    path('account/profile-image/', views.account_profile_image_upload, name='account_profile_image_upload'),
    path('api/chat/', views.chat_with_ai, name='chat_with_ai')
]
