# Generated by Django 5.0.1 on 2024-01-15 07:35

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                (
                    "banner_img",
                    models.ImageField(
                        upload_to=main.models.upload_to_project, verbose_name="대표 이미지"
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                ("create_date", models.DateField(verbose_name="날짜")),
            ],
        ),
        migrations.CreateModel(
            name="Project_Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=128, verbose_name="태그")),
            ],
        ),
        migrations.CreateModel(
            name="Project_Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                ("create_date", models.DateField(verbose_name="날짜")),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.project"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(to="main.project_tag", verbose_name="태그"),
        ),
    ]
