# Generated by Django 5.0.1 on 2024-01-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="question",
            new_name="portfolio",
        ),
    ]
