# Generated by Django 5.0.1 on 2024-01-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project_comment",
            old_name="title",
            new_name="project",
        ),
        migrations.AlterField(
            model_name="project_comment",
            name="create_date",
            field=models.DateTimeField(verbose_name="날짜"),
        ),
    ]
