# Generated by Django 5.0.1 on 2024-01-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_career"),
    ]

    operations = [
        migrations.AddField(
            model_name="career",
            name="period",
            field=models.CharField(default="1년", max_length=128, verbose_name="기간"),
        ),
    ]
