# Generated by Django 5.0.1 on 2024-02-05 15:10

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_career_options_alter_project_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hobby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", main.models.OrderField(blank=True, null=True)),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                (
                    "banner_img",
                    models.ImageField(
                        upload_to=main.models.upload_to_project, verbose_name="대표 이미지"
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
