# Generated by Django 5.0.1 on 2024-04-26 02:26

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stratagem_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gem_class', models.CharField(max_length=128, verbose_name='스트라타잼 분류')),
            ],
        ),
        migrations.CreateModel(
            name='Stratagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', main.models.OrderField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('icon', models.FileField(upload_to=main.models.upload_stratagem, verbose_name='아이콘')),
                ('command', models.TextField(verbose_name='Command')),
                ('stratagem_class', models.ManyToManyField(to='main.stratagem_class', verbose_name='스트라타잼 분류')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
