# Generated by Django 5.0.1 on 2024-04-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_stratagem_class_stratagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stratagem',
            name='command',
            field=models.IntegerField(verbose_name='Command'),
        ),
    ]
