# Generated by Django 5.0.1 on 2024-04-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_stratagem_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stratagem_Hero_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='이름')),
                ('score', models.CharField(max_length=128, verbose_name='점수')),
            ],
        ),
    ]
