# Generated by Django 5.0.1 on 2024-04-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_stratagem_hero_score"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stratagem_hero_score",
            options={"ordering": ["score"]},
        ),
        migrations.AlterField(
            model_name="stratagem_hero_score",
            name="score",
            field=models.IntegerField(verbose_name="점수"),
        ),
    ]
