# Generated by Django 5.0.1 on 2024-04-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_stratagem_hero_score_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stratagem_hero_score",
            name="score",
            field=models.FloatField(verbose_name="점수"),
        ),
    ]
