# Generated by Django 4.2.24 on 2026-02-23 12:21

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_stratagem_hero_score_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciple_icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to=main.models.upload_Disciple_icon, verbose_name='아이콘')),
                ('name', models.CharField(max_length=200, verbose_name='오답')),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(db_index=True, verbose_name='접속 시각')),
                ('request_id', models.CharField(max_length=64, unique=True, verbose_name='요청 ID')),
                ('client_ip', models.CharField(blank=True, max_length=64, verbose_name='클라이언트 IP')),
                ('x_forwarded_for', models.CharField(blank=True, max_length=512, verbose_name='X-Forwarded-For')),
                ('method', models.CharField(blank=True, max_length=16, verbose_name='메서드')),
                ('path', models.CharField(blank=True, db_index=True, max_length=1024, verbose_name='경로')),
                ('query', models.TextField(blank=True, verbose_name='쿼리')),
                ('status', models.IntegerField(db_index=True, verbose_name='상태코드')),
                ('request_time_s', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='요청 처리시간(초)')),
                ('upstream_time_s', models.CharField(blank=True, max_length=64, verbose_name='업스트림 처리시간(초)')),
                ('bytes_sent', models.BigIntegerField(default=0, verbose_name='응답 바이트')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='호스트')),
                ('scheme', models.CharField(blank=True, max_length=16, verbose_name='스킴')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('referer', models.TextField(blank=True, verbose_name='Referer')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='적재 시각')),
            ],
            options={
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['-logged_at', 'status'], name='main_access_logged__3a3814_idx'), models.Index(fields=['request_id'], name='main_access_request_bd8ee3_idx')],
            },
        ),
    ]
