# Generated by Django 4.2.24 on 2026-02-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_disciple_icon_accesslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessLog',
        ),
    ]
