# Generated by Django 4.2.24 on 2026-02-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_accesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='company_en',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='영문 회사'),
        ),
        migrations.AddField(
            model_name='career',
            name='content_en',
            field=models.TextField(blank=True, default='', verbose_name='영문 업무'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_en',
            field=models.TextField(blank=True, default='', verbose_name='영문 내용'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='영문 제목'),
        ),
    ]
