# Generated by Django 4.2.24 on 2026-02-25 02:31

from django.db import migrations, models


def migrate_period_zero_to_open_ended_leave(apps, schema_editor):
    Career = apps.get_model("main", "Career")
    for career in Career.objects.all().only("id", "period", "leave_date"):
        if str(getattr(career, "period", "")).strip() == "0":
            career.leave_date = None
            career.save(update_fields=["leave_date"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_career_company_en_career_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='leave_date',
            field=models.DateField(blank=True, help_text='재직 중이면 비워두세요.', null=True, verbose_name='퇴사일'),
        ),
        migrations.RunPython(migrate_period_zero_to_open_ended_leave, noop_reverse),
        migrations.RemoveField(
            model_name='career',
            name='period',
        ),
    ]
