# Generated by Django 4.2.24 on 2026-02-26 04:57

from django.db import migrations, models


def seed_nav_links(apps, schema_editor):
    NavLink = apps.get_model("main", "NavLink")
    defaults = [
        (1, "GitHub", "https://github.com/Adihang"),
        (2, "Thingiverse", "https://www.thingiverse.com/hanbyel/designs"),
        (3, "Docs", "/docs/list"),
        (4, "Mini Game", "/Stratagem_Hero/"),
    ]

    for order, name, url in defaults:
        NavLink.objects.update_or_create(
            name=name,
            defaults={
                "order": order,
                "url": url,
            },
        )


def unseed_nav_links(apps, schema_editor):
    NavLink = apps.get_model("main", "NavLink")
    NavLink.objects.filter(name__in=["GitHub", "Thingiverse", "Docs", "Mini Game"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_career_period_alter_career_leave_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('name', models.CharField(max_length=100, verbose_name='표시이름')),
                ('url', models.CharField(max_length=500, verbose_name='이동 경로')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed_nav_links, unseed_nav_links),
    ]
