# Generated by Django 4.2.24 on 2026-02-26 18:10

from django.db import migrations


DOCS_EDITOR_GROUP_NAME = "DocsEditors"
DOCS_PERMISSION_CODENAME = "can_edit_docs"
DOCS_PERMISSION_NAME = "Can edit docs content"


def sync_docs_editors_group(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    navlink_content_type, _ = ContentType.objects.get_or_create(
        app_label="main",
        model="navlink",
    )
    docs_permission, _ = Permission.objects.get_or_create(
        content_type=navlink_content_type,
        codename=DOCS_PERMISSION_CODENAME,
        defaults={"name": DOCS_PERMISSION_NAME},
    )

    group, _ = Group.objects.get_or_create(name=DOCS_EDITOR_GROUP_NAME)
    group.permissions.set([docs_permission])


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_navlink"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="navlink",
            options={
                "ordering": ["order", "id"],
                "permissions": [("can_edit_docs", "Can edit docs content")],
            },
        ),
        migrations.RunPython(sync_docs_editors_group, migrations.RunPython.noop),
    ]
