# Generated by Django 4.2.24 on 2026-02-26 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_navlink_can_edit_docs_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, default='', help_text='/docs 기준 상대 경로. 비우면 /docs 루트', max_length=1024, unique=True, verbose_name='경로')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('groups', models.ManyToManyField(blank=True, related_name='docs_access_rules', to='auth.group', verbose_name='허용 그룹')),
                ('users', models.ManyToManyField(blank=True, related_name='docs_access_rules', to=settings.AUTH_USER_MODEL, verbose_name='허용 사용자')),
            ],
            options={
                'verbose_name': '문서 접근 규칙',
                'verbose_name_plural': '문서 접근 규칙',
                'ordering': ['path'],
            },
        ),
    ]
