# Generated by Django 4.2.24 on 2026-02-26 11:23

from django.conf import settings
from django.db import migrations, models


def copy_acl_to_split_fields(apps, schema_editor):
    DocsAccessRule = apps.get_model("main", "DocsAccessRule")
    for rule in DocsAccessRule.objects.all().iterator():
        user_ids = list(rule.users.values_list("id", flat=True))
        group_ids = list(rule.groups.values_list("id", flat=True))
        if user_ids:
            rule.read_users.add(*user_ids)
            rule.write_users.add(*user_ids)
        if group_ids:
            rule.read_groups.add(*group_ids)
            rule.write_groups.add(*group_ids)


def copy_split_fields_to_acl(apps, schema_editor):
    DocsAccessRule = apps.get_model("main", "DocsAccessRule")
    for rule in DocsAccessRule.objects.all().iterator():
        user_ids = set(rule.read_users.values_list("id", flat=True)) | set(
            rule.write_users.values_list("id", flat=True)
        )
        group_ids = set(rule.read_groups.values_list("id", flat=True)) | set(
            rule.write_groups.values_list("id", flat=True)
        )
        if user_ids:
            rule.users.add(*sorted(user_ids))
        if group_ids:
            rule.groups.add(*sorted(group_ids))


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_docsaccessrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsaccessrule',
            name='read_groups',
            field=models.ManyToManyField(blank=True, related_name='docs_read_access_rules', to='auth.group', verbose_name='읽기 허용 그룹'),
        ),
        migrations.AddField(
            model_name='docsaccessrule',
            name='read_users',
            field=models.ManyToManyField(blank=True, related_name='docs_read_access_rules', to=settings.AUTH_USER_MODEL, verbose_name='읽기 허용 사용자'),
        ),
        migrations.AddField(
            model_name='docsaccessrule',
            name='write_groups',
            field=models.ManyToManyField(blank=True, related_name='docs_write_access_rules', to='auth.group', verbose_name='쓰기 허용 그룹'),
        ),
        migrations.AddField(
            model_name='docsaccessrule',
            name='write_users',
            field=models.ManyToManyField(blank=True, related_name='docs_write_access_rules', to=settings.AUTH_USER_MODEL, verbose_name='쓰기 허용 사용자'),
        ),
        migrations.RunPython(copy_acl_to_split_fields, copy_split_fields_to_acl),
        migrations.RemoveField(
            model_name='docsaccessrule',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='docsaccessrule',
            name='users',
        ),
    ]
