# Generated by Django 4.2.24 on 2026-03-02 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_remove_docsaccessrule_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsLoginAttemptGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_attempts', models.PositiveIntegerField(default=0, verbose_name='연속 로그인 실패 횟수')),
                ('captcha_required', models.BooleanField(default=False, verbose_name='캡챠 필요 여부')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docs_login_attempt_guard', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'Docs 로그인 보호 상태',
                'verbose_name_plural': 'Docs 로그인 보호 상태',
            },
        ),
    ]
