# Generated by Django 4.2.24 on 2026-03-04 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_docsloginattemptguard'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='이름')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('icon_url', models.URLField(blank=True, default='', max_length=500, verbose_name='아이콘 URL')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='표시 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_links', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '루트 바로가기',
                'verbose_name_plural': '루트 바로가기',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
