# Generated by Django 4.2.24 on 2026-03-05 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_userthemepreference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserThemePreference',
            new_name='UserProfile',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '사용자 프로필', 'verbose_name_plural': '사용자 프로필'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
