# Generated by Django 4.2.24 on 2026-03-05 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


PORTFOLIO_DEFAULT_USERNAME = "HanbyelLim"


def _seed_default_portfolio_data(apps, schema_editor):
    user_model = apps.get_model(settings.AUTH_USER_MODEL.split(".")[0], settings.AUTH_USER_MODEL.split(".")[1])
    Career = apps.get_model("main", "Career")
    Project = apps.get_model("main", "Project")
    PortfolioProfile = apps.get_model("main", "PortfolioProfile")
    PortfolioCareer = apps.get_model("main", "PortfolioCareer")
    PortfolioProject = apps.get_model("main", "PortfolioProject")
    PortfolioActionButton = apps.get_model("main", "PortfolioActionButton")

    user, _ = user_model.objects.get_or_create(username=PORTFOLIO_DEFAULT_USERNAME)

    profile, _ = PortfolioProfile.objects.get_or_create(user=user)
    if not profile.main_title:
        profile.main_title = "움직이는 풀스텍 개발자, <b>임한별</b> 입니다."
    if not profile.phone:
        profile.phone = "+82-10-7935-3599"
    if not profile.email:
        profile.email = "limhan456@naver.com"
    if not profile.main_subtitle:
        profile.main_subtitle = (
            "자신이 당장 하지 못하는 일이라고 손가락을 빨며 멀리서 지켜 보는 것이 아니라 일단 발을 담궈 봅니다.\n"
            "수동적으로 시키는 일만 하며 멈춰 있는 것이 아닌, 본인이 할 수 있는 일을 계속해서 만들어냅니다."
        )
    if not profile.profile_img:
        profile.profile_img = "profile_removebg.png"
    profile.save()

    existing_career_count = PortfolioCareer.objects.filter(user=user).count()
    if existing_career_count == 0:
        for old_career in Career.objects.all().order_by("-order", "-id"):
            PortfolioCareer.objects.create(
                user=user,
                order=old_career.order,
                company=old_career.company,
                company_en=old_career.company_en,
                position=old_career.position,
                content=old_career.content,
                content_en=old_career.content_en,
                join_date=old_career.join_date,
                leave_date=old_career.leave_date,
            )

    existing_project_count = PortfolioProject.objects.filter(user=user).count()
    if existing_project_count == 0:
        for index, old_project in enumerate(Project.objects.all().order_by("create_date", "id"), start=1):
            new_project = PortfolioProject.objects.create(
                user=user,
                number=index,
                order=old_project.order,
                title=old_project.title,
                title_en=old_project.title_en,
                banner_img=old_project.banner_img,
                content=old_project.content,
                content_en=old_project.content_en,
                create_date=old_project.create_date,
            )
            new_project.tags.set(old_project.tags.all())

    if PortfolioActionButton.objects.filter(user=user).count() == 0:
        PortfolioActionButton.objects.create(
            user=user,
            order=1,
            label="GitHub",
            url="https://github.com/Adihang",
            icon_url="",
        )
        PortfolioActionButton.objects.create(
            user=user,
            order=2,
            label="Thingiverse",
            url="https://www.thingiverse.com/hanbyel/designs",
            icon_url="",
        )


def _rollback_default_portfolio_data(apps, schema_editor):
    user_model = apps.get_model(settings.AUTH_USER_MODEL.split(".")[0], settings.AUTH_USER_MODEL.split(".")[1])
    PortfolioProfile = apps.get_model("main", "PortfolioProfile")
    PortfolioCareer = apps.get_model("main", "PortfolioCareer")
    PortfolioProject = apps.get_model("main", "PortfolioProject")
    PortfolioActionButton = apps.get_model("main", "PortfolioActionButton")

    try:
        user = user_model.objects.get(username=PORTFOLIO_DEFAULT_USERNAME)
    except user_model.DoesNotExist:
        return

    PortfolioActionButton.objects.filter(user=user).delete()
    PortfolioProject.objects.filter(user=user).delete()
    PortfolioCareer.objects.filter(user=user).delete()
    PortfolioProfile.objects.filter(user=user).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_userprofile_delete_userthemepreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='프로젝트 번호')),
                ('order', main.models.OrderField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('title_en', models.CharField(blank=True, default='', max_length=200, verbose_name='영문 제목')),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to=main.models.upload_to_portfolio_project, verbose_name='대표 이미지')),
                ('content', models.TextField(verbose_name='내용')),
                ('content_en', models.TextField(blank=True, default='', verbose_name='영문 내용')),
                ('create_date', models.DateField(verbose_name='날짜')),
                ('tags', models.ManyToManyField(blank=True, to='main.project_tag', verbose_name='태그')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_projects', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '포트폴리오 프로젝트',
                'verbose_name_plural': '포트폴리오 프로젝트',
                'ordering': ['-create_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to=main.models.upload_to_portfolio_profile, verbose_name='프로필 사진')),
                ('main_title', models.CharField(blank=True, default='', max_length=255, verbose_name='메인 타이틀')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='휴대폰번호')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='이메일')),
                ('main_subtitle', models.TextField(blank=True, default='', verbose_name='메인 소개')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '포트폴리오 프로필',
                'verbose_name_plural': '포트폴리오 프로필',
            },
        ),
        migrations.CreateModel(
            name='PortfolioCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', main.models.OrderField(blank=True, null=True)),
                ('company', models.CharField(max_length=128, verbose_name='회사')),
                ('company_en', models.CharField(blank=True, default='', max_length=128, verbose_name='영문 회사')),
                ('position', models.CharField(max_length=128, verbose_name='직책')),
                ('content', models.TextField(verbose_name='업무')),
                ('content_en', models.TextField(blank=True, default='', verbose_name='영문 업무')),
                ('join_date', models.DateField(verbose_name='입사일')),
                ('leave_date', models.DateField(blank=True, help_text='재직 중이면 비워두세요.', null=True, verbose_name='퇴사일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_careers', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '포트폴리오 경력',
                'verbose_name_plural': '포트폴리오 경력',
                'ordering': ['-order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioActionButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='순서')),
                ('label', models.CharField(max_length=40, verbose_name='표시 텍스트')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('icon_url', models.URLField(blank=True, default='', max_length=500, verbose_name='아이콘 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_action_buttons', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '포트폴리오 액션 버튼',
                'verbose_name_plural': '포트폴리오 액션 버튼',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(_seed_default_portfolio_data, _rollback_default_portfolio_data),
        migrations.AddConstraint(
            model_name='portfolioproject',
            constraint=models.UniqueConstraint(fields=('user', 'number'), name='unique_portfolio_project_number_per_user'),
        ),
        migrations.AddConstraint(
            model_name='portfolioactionbutton',
            constraint=models.UniqueConstraint(fields=('user', 'order'), name='unique_portfolio_action_button_order_per_user'),
        ),
    ]
