# Generated by Django 4.2.24 on 2026-03-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_portfolioproject_portfolioprofile_portfoliocareer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioprofile',
            name='main_subtitle_en',
            field=models.TextField(blank=True, default='', verbose_name='영문 메인 소개'),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='main_title_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='영문 메인 타이틀'),
        ),
    ]
