# Generated by Django 4.2.24 on 2026-03-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_portfolioprofile_main_subtitle_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_root_search_engine',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('duckduckgo', 'DuckDuckGo'), ('bing', 'Bing'), ('naver', 'Naver'), ('gpt', 'GPT'), ('claude', 'Claude'), ('gemini', 'Gemini')], default='', max_length=12, verbose_name='루트 검색 엔진'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_ui_lang',
            field=models.CharField(blank=True, choices=[('ko', '한국어'), ('en', 'English')], default='', max_length=2, verbose_name='선호 언어'),
        ),
    ]
