# Generated by Django 4.2.24 on 2026-03-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_userprofile_preferred_root_search_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bumpercar_spiky_stats',
            field=models.JSONField(blank=True, default=dict, verbose_name='범퍼카 스핔이 전적'),
        ),
    ]
