# Generated by Django 4.2.24 on 2026-03-10 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_userprofile_bumpercar_spiky_stats"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocsSharedLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(help_text="/docs 기준 상대 파일 경로", max_length=1024, unique=True, verbose_name="문서 경로")),
                ("share_slug", models.CharField(max_length=255, verbose_name="공유 슬러그")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="docs_shared_links", to=settings.AUTH_USER_MODEL, verbose_name="공유 생성 사용자")),
            ],
            options={
                "verbose_name": "문서 공유 링크",
                "verbose_name_plural": "문서 공유 링크",
                "ordering": ["owner__username", "share_slug"],
            },
        ),
        migrations.AddConstraint(
            model_name="docssharedlink",
            constraint=models.UniqueConstraint(fields=("owner", "share_slug"), name="unique_docs_shared_link_owner_slug"),
        ),
    ]
