# Generated by Django 4.2.24 on 2026-03-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_docssharedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privacy_policy_agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='개인정보 처리방침 동의 시각'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_of_service_agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='이용약관 동의 시각'),
        ),
    ]
