# Generated by Django 4.2.24 on 2026-03-17 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0029_userprofile_privacy_policy_agreed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navlink',
            options={'ordering': ['order', 'id'], 'permissions': [('can_edit_docs', 'Can edit HanDrive content')]},
        ),
        migrations.AlterField(
            model_name='docsaccessrule',
            name='path',
            field=models.CharField(blank=True, default='', help_text='/handrive 기준 상대 경로. 비우면 /handrive 루트', max_length=1024, unique=True, verbose_name='경로'),
        ),
        migrations.AlterField(
            model_name='docssharedlink',
            name='path',
            field=models.CharField(help_text='/handrive 기준 상대 파일 경로', max_length=1024, unique=True, verbose_name='문서 경로'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_root_search_engine',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('youtube', 'YouTube'), ('duckduckgo', 'DuckDuckGo'), ('bing', 'Bing'), ('naver', 'Naver'), ('gpt', 'GPT'), ('claude', 'Claude'), ('gemini', 'Gemini')], default='', max_length=12, verbose_name='루트 검색 엔진'),
        ),
        migrations.CreateModel(
            name='GitUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forgejo_user_id', models.BigIntegerField()),
                ('forgejo_username', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=255)),
                ('forgejo_repo_id', models.BigIntegerField(blank=True, null=True)),
                ('forgejo_owner', models.CharField(blank=True, max_length=255)),
                ('forgejo_repo_name', models.CharField(blank=True, max_length=255)),
                ('forgejo_clone_http_url', models.CharField(blank=True, max_length=1024)),
                ('forgejo_clone_ssh_url', models.CharField(blank=True, max_length=1024)),
                ('handrive_path', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('pending_create', '생성 중'), ('pending_import', '이관 중'), ('active', '활성'), ('failed', '실패'), ('deleted', '삭제됨')], default='pending_create', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('handrive_path',), ('owner', 'repo_name')},
            },
        ),
        migrations.CreateModel(
            name='GitCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=50)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='main.gitrepository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('repository', 'user')},
            },
        ),
    ]
