# Generated by Django 4.2.24 on 2026-03-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_navlink_options_alter_docsaccessrule_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitusermapping',
            name='forgejo_token',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
