"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import json
import mimetypes
import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

mimetypes.add_type("application/javascript", ".js", strict=True)
mimetypes.add_type("application/javascript", ".mjs", strict=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default_csv):
    raw = os.environ.get(name, default_csv)
    return [item.strip() for item in raw.split(",") if item.strip()]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=False)
RUNNING_TESTS = "test" in sys.argv
DEFAULT_SECURE_TRANSPORT = not DEBUG and not RUNNING_TESTS


def load_secret_key():
    secret_key = os.environ.get("DJANGO_SECRET_KEY")
    if secret_key:
        return secret_key

    secrets_path = BASE_DIR / "config" / "secrets.json"
    if secrets_path.exists():
        try:
            with secrets_path.open("r", encoding="utf-8") as file:
                secrets = json.load(file)
        except (OSError, json.JSONDecodeError) as exc:
            raise ImproperlyConfigured(
                "config/secrets.json could not be parsed for SECRET_KEY."
            ) from exc

        secret_key = secrets.get("SECRET_KEY")
        if secret_key:
            return secret_key

    if DEBUG:
        return "local-development-only-secret-key-change-me-please-2026-rotate-this"

    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY (or config/secrets.json SECRET_KEY) is required when DEBUG is False."
    )


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = load_secret_key()


def load_optional_secret(name, default=""):
    from_env = os.environ.get(name)
    if from_env is not None and str(from_env).strip():
        return str(from_env).strip()

    secrets_path = BASE_DIR / "config" / "secrets.json"
    if secrets_path.exists():
        try:
            with secrets_path.open("r", encoding="utf-8") as file:
                secrets = json.load(file)
        except (OSError, json.JSONDecodeError):
            return default
        value = secrets.get(name)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return default

# Ollama (local LLM) settings
OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "llama3.2:latest")
TURNSTILE_SITE_KEY = load_optional_secret("TURNSTILE_SITE_KEY", "")
TURNSTILE_SECRET_KEY = load_optional_secret("TURNSTILE_SECRET_KEY", "")

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    "hanplanet.com,www.hanplanet.com,localhost,127.0.0.1,52.79.71.20,112.187.212.49,112.187.212.140",
)

PUBLIC_BASE_URL = os.environ.get("PUBLIC_BASE_URL", "https://hanplanet.com").rstrip("/")
DJANGO_SERVE_FILES = env_bool("DJANGO_SERVE_FILES", default=True)
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'corsheaders',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "main.middleware.GlobalRateLimitMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True

GLOBAL_RATE_LIMIT_CACHE_ALIAS = os.environ.get("DJANGO_GLOBAL_RATE_LIMIT_CACHE_ALIAS", "rate_limit")
GLOBAL_RATE_LIMIT_CACHE_DIR = os.environ.get(
    "DJANGO_GLOBAL_RATE_LIMIT_CACHE_DIR",
    "/tmp/hanplanet_rate_limit_cache",
)

# Cache settings
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 60 * 60 * 24,  # 24시간 캐시 유지
    },
    'rate_limit': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': GLOBAL_RATE_LIMIT_CACHE_DIR,
        'TIMEOUT': 60 * 60 * 24,
    },
}

GLOBAL_RATE_LIMIT_ENABLED = env_bool("DJANGO_GLOBAL_RATE_LIMIT_ENABLED", default=True)
GLOBAL_RATE_LIMIT_REQUESTS = max(
    1, int(os.environ.get("DJANGO_GLOBAL_RATE_LIMIT_REQUESTS", "240"))
)
GLOBAL_RATE_LIMIT_WINDOW_SECONDS = max(
    1, int(os.environ.get("DJANGO_GLOBAL_RATE_LIMIT_WINDOW_SECONDS", "60"))
)
GLOBAL_RATE_LIMIT_EXEMPT_PATH_PREFIXES = tuple(
    env_list("DJANGO_GLOBAL_RATE_LIMIT_EXEMPT_PATH_PREFIXES", "/static/,/media/")
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# 로깅 설정
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'main': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#     }
# }
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=DEFAULT_SECURE_TRANSPORT)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", default=DEFAULT_SECURE_TRANSPORT)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", default=DEFAULT_SECURE_TRANSPORT)
SECURE_HSTS_SECONDS = int(
    os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "31536000" if DEFAULT_SECURE_TRANSPORT else "0")
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=(DEFAULT_SECURE_TRANSPORT and SECURE_HSTS_SECONDS > 0),
)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=False)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.environ.get("DJANGO_SECURE_REFERRER_POLICY", "same-origin")
X_FRAME_OPTIONS = "DENY"
CSRF_FAILURE_VIEW = "main.docs_views.docs_csrf_failure"

# config/settings.py

# 1) HTTPS에서 CSRF 신뢰 도메인 지정 (Django 4+는 스킴 포함해야 함)
CSRF_TRUSTED_ORIGINS = env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "https://hanplanet.com,https://www.hanplanet.com",
)
